In this eval, we see if the title is the same as the expected title.

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
# load dataset

df = pd.read_csv(
    "./01_article_writer_should_write_with_ground_truth.csv",
    delimiter="|",
    names=[
        "datetime",
        "app",
        "evaluator",
        "model",
        "temperature",
        "title",
        "is_relevant",
        "expected",
        "input_tokens",
        "output_tokens",
        "total_tokens",
        "time_taken",
    ],
)

In [3]:
df.head(3)

,datetime,app,evaluator,model,temperature,title,is_relevant,expected,input_tokens,output_tokens,total_tokens,time_taken
0,2025-07-22-17-42-25,ARTICLE_WRITER,EVALUATOR,gpt-4o-mini,0,The Art of Sourdough: From Starter to Perfect ...,no,no,6,5,0.82,NaN
1,2025-07-22-17-42-25,ARTICLE_WRITER,EVALUATOR,gpt-4o-mini,0,Building Your First AI Agent: A Step-by-Step G...,yes,yes,6,5,0.51,NaN
2,2025-07-22-17-42-35,ARTICLE_WRITER,EVALUATOR,gpt-4o-mini,0,Minimalist Living: How Less Can Mean More,no,no,6,5,0.49,NaN

In [4]:
# comare title with expected

df["equals"]= df["is_relevant"]== df["expected"]
# add this column to the dataframe

# select title, is_relevant, expected, equals,columns
df = df[["title", "is_relevant", "expected", "equals"]]
df.head(5)

,title,is_relevant,expected,equals
0,The Art of Sourdough: From Starter to Perfect ...,no,no,True
1,Building Your First AI Agent: A Step-by-Step G...,yes,yes,True
2,Minimalist Living: How Less Can Mean More,no,no,True
3,Why AI Agents Will Replace Traditional Software,yes,yes,True
4,Urban Gardening in Small Spaces: Maximizing Yo...,no,no,True

In [5]:
# check if all titles match the expected title

if len(df) != sum(df["equals"]):
    print("There are some titles that do not match the expected title.") 
else:
    print("All titles match the expected title.")

percentage_correct = sum(df["equals"]) / len(df) * 100
print(f"Percentage of titles that match the expected title: {percentage_correct:.2f}%")

All titles match the expected title.
Percentage of titles that match the expected title: 100.00%